language: python
branches:
    only:
    - master
    - exctract_class
python:
    - "3.5"
    - "nightly"
install:
    - "pip install ."
    - "pip install pytest"
script:
    - pytest
after_success:
    - "pip install -r requirements_dev.txt"
    - "pip install -e . "
    - "pytest --cov"
