# packages in environment at C:\Users\laurence\AppData\Local\Continuum\Anaconda\envs\http_services:
#
colorama                  0.3.7                    py35_0  
coverage                  4.2                      py35_0  
decorator                 4.0.11                   py35_0  
ipython                   5.1.0                    py35_0  
ipython_genutils          0.1.0                    py35_0  
path.py                   10.0                     py35_0  
pickleshare               0.7.4                    py35_0  
pip                       9.0.1                    py35_1  
prompt_toolkit            1.0.9                    py35_0  
py                        1.4.32                   py35_0  
pygments                  2.1.3                    py35_0  
pytest                    3.0.5                    py35_0  
pytest-cov                2.3.1                    py35_0  
python                    3.5.2                         0  
requests                  2.12.4                   py35_0  
setuptools                27.2.0                   py35_1  
simplegeneric             0.8.1                    py35_1  
six                       1.10.0                   py35_0  
traitlets                 4.3.1                    py35_0  
vs2015_runtime            14.0.25123                    0  
wcwidth                   0.1.7                    py35_0  
wheel                     0.29.0                   py35_0  
win_unicode_console       0.5                      py35_0  
